accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password")
]

products/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.articles, name="articles"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.article_detail, name="article_detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
]

spartamarket_DRF/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', views.main, name='main'),
    path('api/accounts/', include('accounts.urls')),
    path('api/products/', include('products.urls')),
    path('api/users/', include('users.urls')),
    path('', lambda request: redirect('main/')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from products.models import Article
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model


def users(request):
    return render(request, "users/users.html")


def profile(request, username):
    member = get_object_or_404(get_user_model(), username=username)
    user_articles = Article.objects.filter(
        author=member).order_by('-created_at')
    liked_articles = Article.objects.filter(
        like_users=member).order_by('-created_at')

    # 팔로워와 팔로잉 숫자를 계산
    followers_count = member.followers.count()
    following_count = member.following.count()

    context = {
        "member": member,
        "articles": user_articles,  # 사용자의 글 목록을 추가
        "liked_articles": liked_articles,  # 사용자가 찜한 글 목록 추가
        "followers_count": followers_count,
        "following_count": following_count,
    }
    return render(request, "users/profile.html", context)

# 팔로우 기능 구현


@require_POST
def follow(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if member != request.user:
            if member.followers.filter(pk=request.user.pk).exists():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("users:profile", username=member.username)
    else:
        return redirect("accounts:login")

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row justify-content-center mt-4">
    <div class="row mt-4">
        <div class="col-md-6">
            <h2>{{ member.username }}의 프로필 페이지</h2>
        </div>
        <div class="col-md-6 text-end">
            <!-- 내 프로필에서는 팔로우 버튼 안 보이게 하기 -->
            {% if request.user != member %}
            <!-- 팔로우 언팔로우 기능 -->
            <form action="{% url 'users:follow' member.pk %}" method="POST" class="d-inline-block">
                {% csrf_token %}
                {% if request.user in member.followers.all %}
                    <input type="submit" value="언팔로우" class="btn btn-primary">
                {% else %}
                    <input type="submit" value="팔로우" class="btn btn-primary">
                {% endif %}
            </form>
            {% endif %}
            
            {% if request.user == member %}
            <a href="{% url 'accounts:update' %}" class="btn btn-outline-primary d-inline-block me-2">회원정보수정</a>
            <form action="{% url 'accounts:delete' %}" method="POST" class="d-inline-block">
                {% csrf_token %}
                <input type="submit" class="btn btn-outline-primary" value="회원탈퇴">
            </form>
            {% endif %}
        </div>

    </div>
</div>
<div>
    
</div>
<div class="card text-center">
    <div class="card-body">
        <!-- 팔로워 팔로잉 숫자 표시 -->
        <div class="row justify-content-center mt-3">
            <div class="col-auto text-center">
                <h5>팔로워: {{ followers_count }}</h5>
            </div>
            <div class="col-auto text-center">
                <h5>팔로잉: {{ following_count }}</h5>
            </div>
         </div>
{% if member.profile_image %}
    <img src="{{ member.profile_image.url }}" alt="User Profile Image" width="150">
{% else %}
    <img src="{% static 'users/user.png' %}" alt="Default Profile Image" width="150">
{% endif %}

<h3>이름: {{ member.last_name }} {{ member.first_name }}</h3>
<h5>가입일: {{ user.date_joined|date:"Y년 m월 d일" }} </h5>

<h4 align="left">{{ member.username }}님이 작성한 글</h4>

<div class="row row-cols-1 row-cols-md-6 g-4">
    <!-- 내가 작성한 글 보여주기, 제목만 보이게 누르면 그 글로 이동 -->
    {% for article in articles %}
    <div class="col">
        <div class="card" style="width:100px;">
            <a href="{% url 'articles:article_detail' article.pk %}"><img src="{{ article.image.url }}" alt="{{ article.title }}" width="100" height="100"></a>
            <div class="card-body">
                <p class="card-text"><a href="{% url 'articles:article_detail' article.pk %}">{{ article.title }}</a></p>
            </div>
        </div>
    </div>
    {% empty %}
        <div class="col w-100">
            <div>아직 작성된 글이 없습니다.</div>
            {% if request.user == member %}
            <a href="{% url 'articles:create' %}">글 작성하러 가기</a>
            {% endif %}
        </div>
    {% endfor %}
</div>

<br>

<h4 align="left">{{ member.username }}님이 찜한 글</h4>

<div class="row row-cols-1 row-cols-md-6 g-4">
    <!-- 내가 찜한 글 보여주기, 제목만 보이게 누르면 그 글로 이동 -->
    {% for article in liked_articles %}
    <div class="col">
        <div class="card" style="width:100px;">
            <a href="{% url 'articles:article_detail' article.pk %}"><img src="{{ article.image.url }}" alt="{{ article.title }}" width="100" height="100"></a>
            <div class="card-body">
                <p class="card-text"><a href="{% url 'articles:article_detail' article.pk %}">{{ article.title }}</a></p>
            </div>
        </div>
    </div>
    {% empty %}
        <div class="col w-100">
            <div>아직 찜한 글이 없습니다.</div>
            {% if request.user == member %}
            <a href="{% url 'articles:create' %}">글 목록보러가기</a>
            {% endif %}
        </div>
    {% endfor %}
</div>


</div>
</div>
{% endblock content %}

users/templates/users/users.html
{% extends "base.html" %}

{% block content %}
<h1>Users Page</h1>
{% endblock content %}